### ISSUE TITLE
using URT as dll library

### ISSUE THREAD

**Issue by yasharino** [ShabbyX/URT#2]
Dear Mr. Shahbazi
Your job about creating this source is really admirable as we know the number of such statistical tools for programming is limited. I want to use your source as a dll library in mql4 programming to test coinegration of stock market time-series. But mql4 accepts dll importing libraries according to following code. Would you please export URT functions in dll extension with their function description to use in mql4 programming?
Sincerely yours
Yashar

#import "file_name" 
    func1 define; 
    func2 define; 
    ... 
    funcN define; 
#import

Source: https://docs.mql4.com/basis/preprosessor/import

**Comment by ShabbyX** [comment]
First of all this is not a statistical library. This is a library for implementing cross-API realtime programs.

Second, there is no windows support.
